name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.3.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.4
  fluttertoast: ^8.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  photo_view: ^0.14.0
  provider: ^6.0.1
  intl: ^0.19.0
  freezed: ^2.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  go_router: ^14.2.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.17.6 <3.0.0"